name: Deploy Vite Project from docs folder

on:
  push:
    branches: ['main']
    # El flujo solo se activará si cambias algo dentro de la carpeta docs
    paths:
      - 'docs/**'
      - '.github/workflows/deploy.yml' 

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6 # Actualizado

      - name: Set up Node
        uses: actions/setup-node@v6 # Actualizado
        with:
          node-version: 24 # Usamos Node 24 directamente
          cache: 'npm'
          cache-dependency-path: './docs/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: ./docs 

      - name: Build
        run: npm run build
        working-directory: ./docs 

      - name: Setup Pages
        uses: actions/configure-pages@v6 # Actualizado

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5 # Actualizado
        with:
          path: './docs/dist' 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5 # Actualizado